//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
 
package XXsd2CodeSample;
 
 
public	class	CustomerOrder implements Cloneable
{
	public	String	CustomerID;
	public	CreditRating	Rating;
	public	Address	AddressInfo;

	public	java.util.List<XXsd2CodeSample.CommonElements.OrderItem>	Orders;
			
	//default constructor
	public	CustomerOrder()
	{
		CustomerID = "";
		Rating = XXsd2CodeSample.CreditRating.Good ;
		AddressInfo = new Address() ;
		Orders = new java.util.ArrayList<XXsd2CodeSample.CommonElements.OrderItem>() ;
	}
			
	//Clonable Override
	@Override  public	CustomerOrder clone()	throws CloneNotSupportedException
	{
		CustomerOrder	 instance = new CustomerOrder() ;
		instance.CustomerID = CustomerID ;
		instance.Rating = Rating ;
		instance.AddressInfo = (Address)AddressInfo.clone() ;
		instance.Orders.addAll(Orders) ;
		return instance;
	}
			
	//DeepCopy
	public	void DeepCopy(CustomerOrder rhs)
	{
		CustomerID = rhs.CustomerID ;
		Rating = rhs.Rating ;
		AddressInfo.DeepCopy(rhs.AddressInfo) ;
		Orders.addAll(rhs.Orders) ;
	}
			
}


