//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
 
package XXsd2CodeSample.CommonElements;
 
 
public	class	CreditCardDetails implements Cloneable
{
	public	String	CCNumber;
	public	String	ExpirationDate;
	public	FuzzyCondition	Rating;
			
	//default constructor
	public	CreditCardDetails()
	{
		CCNumber = "";
		ExpirationDate = "";
		Rating = XXsd2CodeSample.CommonElements.FuzzyCondition.Hot ;
	}
			
	//Clonable Override
	@Override  public	CreditCardDetails clone()	throws CloneNotSupportedException
	{
		CreditCardDetails	 instance = new CreditCardDetails() ;
		instance.CCNumber = CCNumber ;
		instance.ExpirationDate = ExpirationDate ;
		instance.Rating = Rating ;
		return instance;
	}
			
	//DeepCopy
	public	void DeepCopy(CreditCardDetails rhs)
	{
		CCNumber = rhs.CCNumber ;
		ExpirationDate = rhs.ExpirationDate ;
		Rating = rhs.Rating ;
	}
			
}


