//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
//Auto generated code
 
using System;
using System.Collections.Generic;
 
 
 
 
namespace XXsd2CodeSample
{
	namespace CommonElements
	{
 
		[Serializable]
		public class	OrderItem : ICloneable
		{
			public	bool IsBackOrder; 
			public	string			title;
			public	string			note;
			public	int			quantity;
			public	System.Decimal			price;
			
			//default constructor
			public	OrderItem()
			{
				IsBackOrder = false ;
				title = String.Empty;
				note = String.Empty;
				quantity = 0 ;
				price = default(decimal) ;
			}
			
			//IClonable Override
			public	virtual	object Clone()
			{
				OrderItem	 instance = new OrderItem() ;
				instance.IsBackOrder = IsBackOrder ;
				instance.title = title ;
				instance.note = note ;
				instance.quantity = quantity ;
				instance.price = price ;
				return instance;
			}
			
			//DeepCopy
			public	void DeepCopy(OrderItem from)
			{
				IsBackOrder = from.IsBackOrder ;
				title = from.title ;
				note = from.note ;
				quantity = from.quantity ;
				price = from.price ;
			}
			
		}
	}
}


