//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
//Auto generated code
 
#pragma once
using System::String;
using System::ICloneable;
using System::Collections::Generic::List;
using System::SerializableAttribute;
 
 
 
 
 
 
namespace XXsd2CodeSample
{
	namespace CommonElements
	{
 
		[SerializableAttribute]
		public ref class	OrderItem: public ICloneable
		{
		public:

			[System::Xml::Serialization::XmlIgnore] bool IsBackOrder;
						[System::Xml::Serialization::XmlElement("IsBackOrder")] property int xml_IsBackOrder 
			{ int get() { return IsBackOrder ? 1 : 0; } void set(int value) { IsBackOrder = (value != 0); } }

			String^			title;
			String^			note;
			int			quantity;
			System::Decimal			price;
			
			//default constructor
			OrderItem()
			{
				IsBackOrder = false ;
				title = String::Empty;
				note = String::Empty;
				quantity = 0 ;
				price = 0 ;
			}
			
			//copy constuctor
			OrderItem( OrderItem%  rhs){*this = rhs;}
			
			//IClonable Override
			virtual	Object^ Clone()
			{
				OrderItem^	 instance = gcnew OrderItem() ;
				*instance = *this ;
				return instance;
			}
			
			//= operator
			OrderItem% operator = ( OrderItem%  rhs)
			{
				IsBackOrder = rhs.IsBackOrder ;
				title = rhs.title ;
				note = rhs.note ;
				quantity = rhs.quantity ;
				price = rhs.price ;
				return *this;
			}
			
			//DeepCopy
			void	DeepCopy ( OrderItem^  from)
			{
				IsBackOrder = from->IsBackOrder ;
				title = from->title ;
				note = from->note ;
				quantity = from->quantity ;
				price = from->price ;
			}
			
		};
	}
}


