//Auto generated code
//Code generated by XXsd2Code<http://xxsd2code.sourceforge.net/> XXsd2Code.exe version 1.0.0
//For any comments/suggestions contact code generator author at asheesh.goja@gmail.com
//Auto generated code
//Auto generated code
 
#pragma once
using System::String;
using System::ICloneable;
using System::Collections::Generic::List;
using System::SerializableAttribute;
 
 
 
 
 
 
namespace XXsd2CodeSample
{
	namespace CommonElements
	{
 
		//enumeration	FuzzyCondition
		public enum class	FuzzyCondition
		{
			[System::Xml::Serialization::XmlEnum(Name = "100")] Hot = 100,
			[System::Xml::Serialization::XmlEnum(Name = "200")] VeryHot = 200,
			[System::Xml::Serialization::XmlEnum(Name = "300")] ExtremelyHot = 300,
			[System::Xml::Serialization::XmlEnum(Name = "0")] Cold = 0
			
		};
 
		[SerializableAttribute]
		public ref class	CreditCardDetails: public ICloneable
		{
		public:
			String^			CCNumber;
			String^			ExpirationDate;
			FuzzyCondition			Rating;
			
			//default constructor
			CreditCardDetails()
			{
				CCNumber = String::Empty;
				ExpirationDate = String::Empty;
				Rating = XXsd2CodeSample::CommonElements::FuzzyCondition::Hot ;
			}
			
			//copy constuctor
			CreditCardDetails( CreditCardDetails%  rhs){*this = rhs;}
			
			//IClonable Override
			virtual	Object^ Clone()
			{
				CreditCardDetails^	 instance = gcnew CreditCardDetails() ;
				*instance = *this ;
				return instance;
			}
			
			//= operator
			CreditCardDetails% operator = ( CreditCardDetails%  rhs)
			{
				CCNumber = rhs.CCNumber ;
				ExpirationDate = rhs.ExpirationDate ;
				Rating = rhs.Rating ;
				return *this;
			}
			
			//DeepCopy
			void	DeepCopy ( CreditCardDetails^  from)
			{
				CCNumber = from->CCNumber ;
				ExpirationDate = from->ExpirationDate ;
				Rating = from->Rating ;
			}
			
		};
 
		[SerializableAttribute]
		public ref class	OrderItem: public ICloneable
		{
		public:
			bool IsBackOrder;
			String^			title;
			String^			note;
			int			quantity;
			System::Decimal			price;
			
			//default constructor
			OrderItem()
			{
				IsBackOrder = false ;
				title = String::Empty;
				note = String::Empty;
				quantity = 0 ;
				price = 0 ;
			}
			
			//copy constuctor
			OrderItem( OrderItem%  rhs){*this = rhs;}
			
			//IClonable Override
			virtual	Object^ Clone()
			{
				OrderItem^	 instance = gcnew OrderItem() ;
				*instance = *this ;
				return instance;
			}
			
			//= operator
			OrderItem% operator = ( OrderItem%  rhs)
			{
				IsBackOrder = rhs.IsBackOrder ;
				title = rhs.title ;
				note = rhs.note ;
				quantity = rhs.quantity ;
				price = rhs.price ;
				return *this;
			}
			
			//DeepCopy
			void	DeepCopy ( OrderItem^  from)
			{
				IsBackOrder = from->IsBackOrder ;
				title = from->title ;
				note = from->note ;
				quantity = from->quantity ;
				price = from->price ;
			}
			
		};
	}
}


